POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The Benefits Of GOONING FINAL",
    "author": "Jimbly Jambles",
    "url": "http://test.url.com",
    "likes": 6942069420420
}